### ISSUE TITLE
Alt + F4 closes the app

### ISSUE THREAD

**Issue by AlpSha** [KryDos/todoist-linux#40] opened 2019-04-12 18:14 UTC
I am using Ubuntu 18.04 and when i use alt+f4 even on another window, alt+f4 first kills todoist and i need to press one more to alt+f4 in order to close my current window. It doesn't matter which window is active, first alt+f4 always closes todoist from background if it is running. Like i am writing on chrome right now, and todoist is running on background. I did press alt+f4 and todoist has been closed, i am still writing.

**Comment by cyfrost** [comment] 2019-04-12 19:17
Yet another "Global Shortcut ruined it" issue :P @krydos

**Comment by KryDos** [comment] 2019-04-13 14:04
Yep, one more wrongly bound global shortcut :D 

Thanks for report @Anrchst93 I hope we can fix this issue pretty soon. 
For workaround on your side you can take a look at my comment [HERE](https://github.com/KryDos/todoist-linux/issues/38#issuecomment-478541561). We had very similar issue but for `F11` shortcut.

**Comment by Anrchst93** [comment] 2019-04-15 08:47
I fixed with your help, thanks a lot. Whatever shortcut i give it, it works as global. Anyway i just set it as i wish to use.

**Comment by laszukdawid** [comment] 2019-05-12 18:27
Hey, just checked out this app and seems that will be my new best friend. Thanks 👍
On this issue... why do you even have `"quit": "ALT+F4"` ([line](https://github.com/KryDos/todoist-linux/blob/master/src/shortcutConfig.js#L93))? By default, system handles this for you; it will emit 'close' event to any active window. I know you are working on this for the next release but just curious why that line is there even?

**Comment by KryDos** [comment] 2019-05-12 18:32
hi @laszukdawid, 
thanks for the kind words about the app :)

`alt-f4` in our case quit the app completely. By default the app is just hiding to tray when `close` event is received.

**Comment by laszukdawid** [comment] 2019-05-12 18:40
Oh, nice, got a thumbs down for asking a question :)

Ok, I see. Although I'm unable to reproduce hiding behaviour. After removing that line from the code, hitting `ALT+F4` on active Todoist kills it completely without a trace of the process. Anyway, my issue is solved and was just curious for the line.

Thanks again for the app!

**Comment by KryDos** [comment] 2019-05-12 18:48
LOL, excuse me about thumb down, I hope it was accidental. 
That's pretty strange that in your case alt+f4 close the app and doesn't hide it to tray. Does the app shows in tray at all? (we previously had few issues related to tray on some distros).

**Comment by laszukdawid** [comment] 2019-05-12 19:01
Yep. On execution (`make up`), I see the Todoist icon in my tray panel. When I hide the app (icon click -> hide) it disappears from available windows but persists in the tray. (icon click -> show) makes the app in focus. I can switch windows and all. When the Todoist-app is in focus `ALT+F4` kills it and removes from the tray. 

When running the Todoist app as detached task it spawns 5 processes (`ps aux`). When hitting `ALT+F4` on active app no processes are left.

I'm running Ubuntu 18.04.2 LTS with `XDG_CURRENT_DESKTOP=ubuntu:GNOME`. Will check tomorrow (~24h) whether it's the same thing on Ubuntu 16.04.

**Comment by mpeshev** [comment] 2019-10-22 19:48
Thanks for the Todoist Electron build in the first place!

I think that alt + f4 is an excessive config option (a default one) but I appreciate the opportunity to override it from the json config.

**Closed** 2021-01-15 09:05 UTC
