### ISSUE TITLE
Cannot sign in with google account

### ISSUE THREAD

**Issue by jonchampagne** [KryDos/todoist-linux#59] opened 2019-12-15 23:25 UTC
I know this is a problem from google primarily, but should probably be documented somewhere obvious, perhaps with some sort of workaround. 

Anyways, when trying to sign in to todoist with a google account, I get an error message saying "this browser or app may not be secure". This makes it impossible to sign in with a google account. 

![image](https://user-images.githubusercontent.com/1485633/70870982-21254b80-1f92-11ea-96ca-5661dcca4dd3.png)

**Comment by KryDos** [comment] 2019-12-16 09:17
Wow. Google :( 

Thanks for the report @jonchampagne, I'll take a look. I hope it can be fixed by changing the user agent of the app.

**Comment by Donboscow** [comment] 2019-12-20 14:38
Still I'm facing this problem. Can't log in with Google Account.

**Comment by KryDos** [comment] 2019-12-20 18:55
hey guys, 
The issue should be fixed with the newer version of the app. [Check this release](https://github.com/KryDos/todoist-linux/releases) and let me know please if the issue is resolved. 

I've added a user-agent header to all the requests from the app so it now pretends to be a Google Chrome browser on Windows.

**Comment by hellmrf** [comment] 2020-11-23 21:30
Shouldn't this issue be closed, as the problem is solved?

**Comment by KryDos** [comment] 2020-11-28 12:48
Make sense, closing it. Thanks @hellmrf

**Closed by KryDos** 2020-11-28 12:48 UTC
