### ISSUE TITLE
Can't adjust font size or window zoom

### ISSUE THREAD

**Issue by ilyesLtifi** [KryDos/todoist-linux#61] opened 2020-01-18 14:24 UTC

**Comment by KryDos** [comment] 2020-01-18 14:31
hi @ilyesLtifi, 
You can zoom in with `ctrl+shift+=` and out with `ctrl+-`. You can also go to `View` section of the menu and find `Zoom In` or `Zoom Out` items there. 

Currently there is no way to remember the zoom you set before so if app is restarted then you need to adjust the zoom level again.

**Comment by ilyesLtifi** [comment] 2020-01-18 15:18
Hello @KryDos

None of those shortcuts work.
Also where is this "View" section?

Is it possible that I'm using an older version or something? I downloaded the latest version today, yet there is no mention of "View" or "Zoom" in the settings. Also I don't have those shortcuts listed in the "Keyboard shortcuts" menu.

**Comment by KryDos** [comment] 2020-01-18 15:19
interesting. @ilyesLtifi could you please send me your specs (Linux distro, Desktop environment and its version). Screenshot of the window would be good to see as well.

**Comment by ilyesLtifi** [comment] 2020-01-18 15:25
Im am on KDE Neon.

I used _dpkg -i_ to install the .deb installation file.

![distro](https://user-images.githubusercontent.com/38229094/72666082-10dc1280-3a0f-11ea-9370-a45c2be879f4.png)

**Comment by KryDos** [comment] 2020-01-18 15:27
I actually didn't use the app with KDE before. Could you please attach the screenshot of the Todoist app window too. I will install KDE a bit later on my test machine and let you know the result. 

Thanks for letting me know about the issue!

**Comment by ilyesLtifi** [comment] 2020-01-18 15:35
Happy to help :)

Here is a screenshot of the window bar and the top menu.
![todoist](https://user-images.githubusercontent.com/38229094/72666211-5a792d00-3a10-11ea-80dd-6af22de90199.png)

I understand what you meant now with "menu"; the standard menu bar in every application. As you can see it wasn't there from the start.

Also, there seems to be an issue with the sync. I got that error icon at the top, when I click on it I get this:
![erorr](https://user-images.githubusercontent.com/38229094/72666241-7da3dc80-3a10-11ea-83d9-3b356594cf9c.png)

When I click on "Try to sync again" it loads a bit then stays the same.

**Comment by ShaneEverittM** [comment] 2020-03-14 20:53
Any update on this?

**Comment by KryDos** [comment] 2020-03-14 20:59
hi @ShaneEverittM, 
I wasn't able to reproduce it, so no updates... 
What Desktop Environment (Gnome, KDE, Xfce, etc..) do you have on your machine? Have your tired `ctrl+shift+=` shortcut?

**Comment by ShaneEverittM** [comment] 2020-03-14 21:16
@KryDos I am also on KDE Neon, yes I tried ctrl+shitf+=

**Comment by KryDos** [comment] 2020-03-14 21:43
ah, I did not install KDE on my machine to test this issue.  
I don't think I can install KDE at the moment on my machine but I can try to do it in virtual machine. I can't estimate when I'll do it but as soon as I test this issue in KDE I'll post the result here.

**Comment by WarmongeringBeaver** [comment] 2020-03-30 12:36
Same problem for me with this setup:
Kubuntu 19.10
KDE Plasma 5.18.3
KDE Frameworks 5.67.0
Qt 5.12.4
Couldn't find any workaround to zoom in : (

**Comment by ppwwyyxx** [comment] 2020-04-02 08:18
I found that if I build the project manually with the instructions in https://github.com/KryDos/todoist-linux#build-instructions, my window has the "View" tab and can be zoomed with shortcuts mentioned above.

However when I build the project in archlinux's aur, I met the same issues mentioned above: no "View" tab and keys don't work.

**Comment by KryDos** [comment] 2020-04-02 08:25
Nice! Thanks for digging into it @ppwwyyxx. I'll try to reproduce it with steps you mentioned.

**Comment by ppwwyyxx** [comment] 2020-04-02 08:27
Seems the same issue as https://github.com/electron/electron-packager/issues/131

**Comment by furkanunluturkk** [comment] 2020-04-05 10:11
yep, same issue here... 

> I found that if I build the project manually with the instructions in https://github.com/KryDos/todoist-linux#build-instructions, and run it with ` npm run start`, my window has the "View" tab and can be zoomed with shortcuts mentioned above.
> 
> However after I build it with `make build-pacman` and run the package, I met the same issues mentioned above: no "View" tab and keys don't work.

yep, same issue here... configurations has to remain after the building though...

**Comment by KryDos** [comment] 2020-04-05 15:24
Yeah, so when I run the app I use `npm start` and in this case the menu is present and all shortcuts bind to the menu also work.
When we run the "production" build of the app there is no menu and no shortcuts related to that menu. 

That make sense and explains why I couldn't reproduce this issue and the issue with Full Screen (https://github.com/KryDos/todoist-linux/issues/48)

I don't see easy-fix for this right now. I definitely don't like a custom menu bar (more code, more complexity and more bugs) but we probably should go this way... I'll research this better

**Comment by ppwwyyxx** [comment] 2020-04-06 00:35
Since what we need is the functionality rather than the menu bar, it might make sense to add shortcuts for zooming.

**Comment by stefan2904** [comment] 2020-05-17 22:15
I use this command to start the app with increased font size:

`todoist --high-dpi-support=1 --force-device-scale-factor=1.5 &`

(this works for all electron apps, I think.)

**Closed** 2021-01-15 09:05 UTC
