### ISSUE TITLE
Cannot exit fullscreen mode

### ISSUE THREAD

**Issue by batjko** [KryDos/todoist-linux#48] opened 2019-06-12 17:07 UTC
Related to #38, I suppose.

When I use the Toggle fullscreen menu item in the notification bar icon menu, I am unable then to exit fullscreen again.
F11 does nothing.
Hitting "toggle fullscreen" again, does nothing (Luckily I have a second screen so I can even get to that menu). 

What do I need to do?

**Comment by KryDos** [comment] 2019-06-12 17:10
hey @batjko, thanks for report. Not sure if #38 is related here since you use "toggle fullscreen" from tray (as far as I got).

Could you please share your os, distro, desktop environment.

**Comment by batjko** [comment] 2019-06-12 21:33
Ah yes, apologies:    Linux, Ubuntu 18.10 64bit.

**Comment by KryDos** [comment] 2019-06-14 16:55
I was trying to reproduce it on my only currently available Linux (Ubuntu 18.04) but no luck. 
 
Could you please share output of  `gnome-shell --version`

**Comment by cyfrost** [comment] 2019-06-16 04:56
I'm able to reproduce this bug on Fedora 30 KDE on an X session.

Right click Todoist tray icon > Click Toggle Full Screen > press F11 to get out / press ESC to get out > doesn't work.

Finally, I had to alt+tab to another app and then close Todoist that way.

I'm vouching for the removal of Toggle Full Screen option, though.

**Comment by philipp-r** [comment] 2019-07-05 14:43
I have the same problem with Ubuntu 18.04.2 LTS and GNOME Shell 3.28.4.

Toggle fullscreen with F11 works fine in other programs just not in Todoist.

**Comment by KryDos** [comment] 2019-07-07 12:56
hey @philipp-r, thanks for the info. 

I'm currently on the same Ubuntu and GHOME shell version. Still works for me...

Could you please share your `~/.config/.todoist-linux.json` with me. Also let me know please if you use Wayland or Xorg. 

I just tried to do full screen with GNOME on Wayland and all my RAM was eaten up immediately...  I hope it something on my machine only...

**Comment by philipp-r** [comment] 2019-07-09 16:21
I'm using Xorg. I have not tested it with Wayland. 

This is my `~/.config/.todoist-linux.json`: 
``` 
{
    "quick-add": "CommandOrControl+Alt+a",
    "show-hide": "CommandOrControl+Alt+Q",
    "refresh": "CommandOrControl+Alt+r",
    "quit": "Alt+F4"
}
```

**Comment by dlecan** [comment] 2019-12-23 08:03
Todoist Linux 1.19, Ubuntu 18.04, Xorg, GNOME Shell 3.28.4, same config file as @philipp-r:
- F11 doesn't work
- Impossible to exist full screen mode whent toggling 

Before #38, I was able to toggle the app fullscreen with F11 (but impossible to do with Firefox)

**Comment by sollymay** [comment] 2019-12-26 04:15
Same here with Elementary OS (based on Ubuntuo 18.04 and Wayland). seems like the app when started creates two separate windows (one full screen and one non full screen). You can pretty much use F11 to go to the non full screen window but you need to close the full screen window first as it seems the full screen window overlaps the non full screen window). It also, for some reason start the non full screen version in a separate workspace instead of the one that it is initially invoked on.

**Comment by sollymay** [comment] 2019-12-26 04:22
Seems like the issue is fixed with the latest version of the app. At least I was able to switch to full screen and out using F11 no problem! try to install that new version @dlecan @batjko @philipp-r

**Comment by KryDos** [comment] 2019-12-26 06:47
LOL, I didn't try to fix it in newer version but I'm happy it seems fixed somehow. 

Thanks @sollymay for testing and letting everybody know!

**Comment by RHCPNG** [comment] 2020-03-22 07:40
I have the same problem on Linux Mint 19, I can't get out of full screen. I'm going to re-install and try again

**Comment by pfluegdk** [comment] 2020-03-31 13:18
I have the same problem on Ubuntu 18.04.4 LTS, GNOME Shell 3.28.4, Todoist Linux 1.19 from the releases website (deb installed).
Plus, if I select "Popout in a window" from the menu, the app crashes and restarts full screen. Alt+F4 successfully kills it, but that is the only way to get rid of the fullscreen.

**Comment by jester02k** [comment] 2020-04-03 14:36
Same here Linux mint 19 starts in full screen unable to leave have to open a new browser to be able to toggle to a smaller window that I just leave open.

**Comment by pfluegdk** [comment] 2020-04-14 22:06
I just installed Version 1.21 (deb-package) - no change.
Then I stumbled over #61, thanks to @KryDos reference to that issue!, and followed the manual build instructions rather than using the deb-package.
Starting todoist with "npm run start" still starts the window fullscreen. But now F11 works and I get a window back.

**Comment by michael-wenyon** [comment] 2020-05-15 16:18
I just experienced this 'stuck in fullscreen' effect in Debian Buster 10. I could not find 'Toggle Fullscreen' at first, but it was in the toolbar menu not the app, and it did the job from there after I alt-tabbed out of Todoist.

**Closed** 2021-01-15 09:05 UTC
