### ISSUE TITLE
Disable / Change F11 when conflicting

### ISSUE THREAD

**Issue by BatmansGehilfe** [KryDos/todoist-linux#38] opened 2019-04-01 09:59 UTC
How can I disable or change the full screen shortcut (F11)? It conflicts with firefox on my system.

**Comment by cyfrost** [comment] 2019-04-01 10:15
@BatmansGehilfe Did you mean to say that F11 of Todoist is registered as a global shortcut and is conflicting with Firefox? If yes, did you happen to notice that with other apps too? For instance, with Todoist open (but NOT focused), try F11'ing chrome maybe?

**Comment by KryDos** [comment] 2019-04-01 11:28
hey @BatmansGehilfe, thanks for letting us know about it. 

I was just able to reproduce it. It happens because our F11 is set globally. So even if you are in Firefox or any other app, F11 will full screen the todoist instance anyway. 

As a workaround you can edit your `$XDG_CONFIG_HOME/.todoist-linux.json` and line `"toggle-fullscreen": "F11"` in particular. Just change F11 to something else. 

If you have no such line in your config file then you need to add it. But make sure JSON is correct (every line except last one should end with comma).

@cyfrost thanks for jump in!

**Comment by BatmansGehilfe** [comment] 2019-04-01 16:17
thanks @cyfrost and @KryDos ! That was both extremely helpful and quick. @KryDos hint actually worked - there was no such line present in my file.

**Comment by KryDos** [comment] 2019-04-01 16:39
🎉 I'm glad this issue is resolved for you. 

I'll keep this one opened for awhile just to make sure Globally bound F11 is changed to locally bound.

**Comment by karthikiyengar** [comment] 2019-04-08 08:03
I actually had the same issue. Would it be possible to just opt out of certain shortcuts? Removing the line from the config just results in falling back to the default. I have mapped fullscreen to some obscure key combination because I don't use it that much, but it'd be nice to not pollute global shortcuts if possible.

**Comment by KryDos** [comment] 2019-04-08 10:00
@karthikiyengar yeah, unfortunately removing the line from config file just falls back to defaults. Solution you came up with is the only possible currently. We'll make the change and new version of the app should not contain this issue. 

Maybe we should just remove shortcut for full screen... I don't think it is a functionality that needs a shortcut. 

I'll post here when new version is ready.

**Comment by cyfrost** [comment] 2019-04-08 10:44
> Maybe we should just remove shortcut for full screen... I don't think it is a functionality that needs a shortcut.

Just putting my feeling about this: I think so too, I've trouble remembering the last time I F11'ed Todoist, for all practical purposes, the Maximized view is quite sufficient for me.

Maybe you can get rid of F11 shortcut and add it if someone raises a feature request for it :)

**Comment by KryDos** [comment] 2019-04-09 18:37
hey guys,
Please take a look at [Release 1.16](https://github.com/KryDos/todoist-linux/releases/tag/1.16) where this issue is fixed. 

F11 isn't globally bound anymore. At the same time it does work inside the app. 

I'm closing the issue. Let me know if you still see the bug.

**Closed by KryDos** 2019-04-09 18:37 UTC
