### ISSUE TITLE
[Bug] The main window doesn't load first time after log in

### ISSUE THREAD

**Issue by AlexeyKot** [KryDos/todoist-linux#5] opened 2018-05-03 09:57 UTC
When I first install the app and entered my log in and password, it shows me that everything is good, wait till the main window will appear on click on the link if it doesn't. It didn't appear, but when I clicked on the link to manually refresh the page, the second window was opened, while the old window was still there. 
When I restarted the app - everything was fine.

**Comment by KryDos** [comment] 2018-05-03 12:39
Saw it once as well. Will try to reproduce it with clear setup in VM.  Thanks!

**Comment by KryDos** [comment] 2018-05-19 15:54
hey @AlexeyKot 
The app was opening all links in an external browser but some of the links should be opened in the app itself. Because of this reason the whole integrations page wasn't working too. 

The fix is in 1.7 version - https://github.com/KryDos/todoist-linux/releases/tag/1.7

**Closed by KryDos** 2018-05-19 15:54 UTC
