### ISSUE TITLE
Links not opened in system default browser

### ISSUE THREAD

**Issue by jrabensc** [KryDos/todoist-linux#120] opened 2020-10-08 06:53 UTC
OS: Latest Manjaro running Gnome 3.36.6
Version: 1.24.0-4

Since the update, links within tasks are opened in a native window and not in the system default browser. To open a link in Firefox, I need to manually copy the URL from the task title.

This behavior should be controlled by the settings file.

**Comment by KryDos** [comment] 2020-10-08 11:29
hi @jrabensc, thanks for the report. 
This is not intended behavior and external links should open in system default browser. 

I hope it will be fixed quickly, I'll let you know

**Closed** 2021-01-15 09:04 UTC
