### ISSUE TITLE
Alt+F4 closes Todoist even if the window is not active

### ISSUE THREAD

**Issue by mikkovedru** [KryDos/todoist-linux#65] opened 2020-03-29 02:27 UTC
Alt+F4 closes Todoist even if the window is not active.

Documentation:
>Keyboard Shortcuts
>Alt+F4 - Quit Todoist

And it works. Globally. Meaning that pressing Alt+F4 in any window anywhere, closes todoist-linux window.

It really shouldn't. Alt+F4 is one of the most widely known and popular hotkeys. It shouldn't just be stolen from the whole system in order to use it for one program only in a very uncommon scenario of "I want to close todoist-linux competely while not having that window open".

Reproduction:
1. Start todoist-linux
2. Hide it with the global Show or Hide Todoist window hotkey (Ctrl+Alt+Q)
3. Go to any other program.
4. Try to close it using the standard Alt+F4 key. You see that the first press does nothing (because it is closing todoist-linux; you can see it by trying to press Ctrl+Alt+Q - todoist window won't show up)
5. Next Alt+F4 press actually closes that "other" program.

**Comment by KryDos** [comment] 2020-03-30 09:00
Yeah, all our keybindings are global. The way I see it now is we need only one global keybinding (to quickly add a note) and everything else should be local (when app is opened and focused). 

We have this issue for a long time already and the only workaround here is to remove keybinding from config file or re-bind it to something unusual. 

I definitely should spend some time making local keybindings. I'll try to find time for this as soon as possible.

**Comment by mikkovedru** [comment] 2020-03-30 09:25
"Show or Hide Todoist window" should also obviously be global.

Is it possible to remove the global Alt+F4 from the program completely? Wouldn't OS take over and make Alt+F4 still work, but only when the window is active?

**Comment by KryDos** [comment] 2020-03-30 09:29
Currently when the app is getting "quit" event from OS it just hides itself and doesn't actually quits. So Alt+F4 was redefined to force the app to quit. So this is why we have this keybinding in the app. I guess it's useful to have at least until we have some kind of configuration interface where user can choose what to do when "quit" event is received (I personally don't want this interface).

**Comment by mikkovedru** [comment] 2020-03-30 09:54
Now it makes more sense. Thank you for explaining.

**Comment by Dude29** [comment] 2020-06-26 16:41
> I guess it's useful to have at least until we have some kind of configuration interface...

I agree but wouldn't it make more sense to be a local shortcut instead of a global one?
That way the app would only respond to the quit shortcut if it was in focus

I looked at the source and it doesn't seem too difficult to implement this, if you want I can make the changes to the code

**Comment by KryDos** [comment] 2020-06-26 20:56
Yeah, that's unfortunately how I initially implemented it (using global shortcuts). Alt+f4 obvously shouldn't be global and if you (@Dude29) can help me to fix it I'll be super happy

**Comment by Dude29** [comment] 2020-06-27 21:57
OK no problem, I'll make a PR 👍

**Comment by KryDos** [comment] 2020-06-29 18:26
The fix is in the latest 1.23 release now! 🕺

**Comment by FindHao** [comment] 2020-08-18 15:42
I'm in v1.23. But this problem still exists.

**Comment by KryDos** [comment] 2020-08-19 10:49
thanks @FindHao for the report. I'll take a look

**Comment by Dude29** [comment] 2020-08-19 13:43
> I'm in v1.23. But this problem still exists.

Hi! 
Could you describe the environment in which you are running the app?
Which distro are you using and your display environment?

**Comment by FindHao** [comment] 2020-08-19 13:57
> > I'm in v1.23. But this problem still exists.
> 
> Hi!
> Could you describe the environment in which you are running the app?
> Which distro are you using and your display environment?

Ubuntu 20.04.1 X86_64
Xorg
Two monitors

**Comment by Dude29** [comment] 2020-08-19 18:48
Ok this issue might be a little more complicated than expected.

I have the same environment as you with the exception of having only one monitor and I was unable to reproduce this problem on 1.23
I tested it by presing ALT+F4 while having Todoist open but with the file browser focused instead and the behavior was correct: Todoist did not close.
I think what may be happening is that electron is not recognizing, somehow, that the window is not focused but i'm not sure what can be causing that interference. 
I'm sorry, I wish I could be more helpful

**Comment by KryDos** [comment] 2020-08-20 07:08
@Dude29 this is pretty good idea on what is going on. Thanks!
I wonder if I can reproduce it on my side. I'll post here the result

**Comment by Araly** [comment] 2020-10-01 23:30
hey, just found this issue as I was searching what was hijacking my alt-f4, so I'll add the behaviour I see on my end.

I'm using todoist-electron from the AUR which I believe pulls from this repo. Whenever Todoist is running, alt-f4 doesn't work, unless the todoist window is focused. If todoist is focused, alt-f4 kills the whole todoist process. If todoist isn't focused, alt-f4 does nothing, it doesn't kill the window I have focused, exactly as if I had disabled the shortcut in gnome.

Hope this gets fixed, it was a weird hunt to search for what the hell I had done to my computer for alt-f4 not to work anymore ^^ I'll see if I can tinker around a bit.

**Comment by KryDos** [comment] 2020-10-02 13:37
hey @Araly,
yeah, it is a long time issue. You can fix it by changing (or by adding)  the `quit` key in your `~/.config/.todoist-linux.json` file. Bind that `quit` action to something else and it must free Alt-F4 shortcut for the OS. 

As I mentioned above the app use Alt+F4 as a global shortcut and if the app is running(not necessary active) then that shortcut is controlled by the app. 
That's not intended behavior and I hope at some point it will be fixed.

**Comment by mikkovedru** [comment] 2020-10-05 23:43
@Araly 
And to add to @KryDos 's suggestion, this is what I wrote in my `.todoist-linux.json` file:
> "quit": "Alt+F14"

F14 button doesn't exist on my keyboard = this hotkey combination will not clash with anything useful, even accidentally.

**Comment by vikrend** [comment] 2020-10-07 20:29
I have the same behavior as @Araly when Alt+F4 won't work with any other app focused. Tried to remap it to different combination in config file but had no luck: the app just says that config is wrong and ignores it. I really need my ALT+F4 :)

**Closed** 2021-01-15 09:05 UTC
